name: Sufiitrq1-DevOps-Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Fetching Code
      uses: actions/checkout@v4

    - name: 2. Preparing PHP Environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: 3. Validating Project Files
      run: composer validate

    - name: 4. Running Automated Tests
      run: composer test
